FROM node:20-alpine

WORKDIR /app

# Copy only package files to leverage the cache
# Dependencies are downloaded only when these files are modified
COPY package.json package-lock.json ./
RUN npm ci

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host"]