FROM golang:1.24-alpine

# Install git (for go modules) and air (for live reload)
RUN apk add --no-cache git \
    && go install github.com/air-verse/air@v1.61.1

# Working directory inside the container
WORKDIR /app

# Copy go.mod and go.sum only, to leverage the docker's cache
# Dependencies get downloaded when these files are modified

COPY go.mod go.sum ./
RUN go mod download

EXPOSE 1313

CMD ["air"]