name: Backend CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23

      - name: Cache Go Modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('backend/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install Dependencies & Tidy
        working-directory: backend
        run: |
          go mod tidy
          go mod download

      - name: Run Tests
        working-directory: backend
        run: go test -v ./... # this will help us test all the folders

      - name: Build Backend
        working-directory: backend/cmd/server # i m doing this to test only main.go in cmd/server
        run: go build -v .

      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s latest 

      - name: Run Linter
        working-directory: backend
        run: ../bin/golangci-lint run